; All lines starting with a semicolon ";" are ignored.

[Pages]
; Maximum allowed page size
; Allowed values are: 
;    * Letter (US Letter page 8.5 x 11 in)
;    * A<k> (A series international paper size standard A0 to A10)
;    * DL (DIN long paper size 99 x 210 mm)
;    * <w> x <h> <uu> Arbitrary page size of width <w>, height <h> measured in units <uu>. Supported units are in, pt, cm, and mm
MaxPageSize=A4
; Size tolerance in points for the page size validation for each dimension. 
; The default value is 3 points when nothing is specified.
SizeTolerance=18

[File]
; Require document not to be with a bigger version than MaxPdfVersion.
; Allowed format is major.minor with major and minor integers
MaxPdfVersion=1.7
; Require file to be encrypted or not depending on the value of Encryption
Encryption=false
; File size must not exceed FileSize (value in MB)
FileSize=250

[Fonts]
; The Embedding setting can be used to test the embedding of fonts that are used for rendering. 
; EmbeddingExcFont‹i› keys define a list of fonts exempt from the Embedding rule.
; When Embedding is true, all fonts should be embedded unless they are explicitly allowed to be unembedded by being listed in the EmbeddingExcFont list.
; When Embedding is false, fonts should not be embedded unless they are listed in the EmbeddingExcFont list.
; You can use wildcards on the font names.
Embedding=true 
EmbeddingExcFont1=Courier*
EmbeddingExcFont2=Helvetica* 
EmbeddingExcFont3=Symbol* 
EmbeddingExcFont4=Arial* 
EmbeddingExcFont5=LetterGothic*
EmbeddingExcFont6=Unknown*
